### ISSUE TITLE
Question about MERL dataset filter

### ISSUE THREAD

**Issue by bearprin** [ryushinn/meta-sampling#1]
Hi

Thanks for your work. I recently learned many things from your elegant code.

But I have a few questions want to raise.

I notice both of you and NBRDF [Sztrajman 21] only remove the invalid MERL data by checking the R channel.

I am confused as to why not also remove the invalid data by checking G and B channels, as [dj_brdf](https://github.com/jdupuy/dj_brdf) does.

Looking forward to your reply

**Comment by ryushinn** [comment]
AFAIR, the MERL data marks invalid regions by setting them as -1 for all channels so checking only the R channel would be enough.

**Comment by ryushinn** [comment]
I close this issue since it's not active now. Please let me know if you have any other questions.
